### PR TITLE
Fast combine

### PR DESCRIPTION
**Pull request by Kukunin**
Use faster version of Ruby based combine. There is native C implementation, but it's only 3x times faster, while previous implementation was 28286x slower than native one.

https://files.gitter.im/rom-rb/chat/JI2y/blob

So, this PR gives huge boost to #combine method

### CODE REVIEW

**Comment by Kukunin** [comment]
Use faster version of Ruby based combine. There is native C implementation, but it's only 3x times faster, while previous implementation was 28286x slower than native one.

https://files.gitter.im/rom-rb/chat/JI2y/blob

So, this PR gives huuge boost to `#combine` method

**Comment by Kukunin** [comment]
`rom-mapper` and `rom-repository` works fine with new `#combine`

**Comment by splattael** [comment]
:heart: :heart: :heart:

**Comment by splattael** [comment]
Should we keep the benchmark?

**Comment by solnic** [comment]
@splattael what would it do?

**Comment by splattael** [comment]
Sit there and wait for future improvements? But yeah, it's probably fast enough! :D

**Comment by solnic** [comment]
@splattael we could have a small bench infrastructure so that it's easy to setup a bench for a specific method during optimization refactors, but it's not a 3 minute task so I'm postponing it. I'll push what we have to a branch so that we can have it accessible for future reference.

**Pull request merged**
