### PR TITLE
[WIP] Use Registry in all function containers

### PR DESCRIPTION
**Pull request by solnic**
### TODO

- [x] A couple of specs are failing for error handling and ast
- [x] Add deprecation warnings to `Transproc()`
- [x] Add deprecation warnings to `Transproc.register`
- [x] Update modules to use `uses` interface when needed

### CODE REVIEW

**Comment by solnic** [comment]
How are we doing here? Possible to wrap this up soon? Would be cool to release 0.3.0 with proper deprecation warnings :) I'll also add `:evaluate` transformation which calls lazy-values recursively which I use at work :)

**Comment by nepalez** [comment]
Yes, I think we can. I have no other ideas for this release :)

**Comment by solnic** [comment]
Are you planning to push some more changes to this branch?

**Comment by nepalez** [comment]
No

**Pull request merged**
