### PR TITLE
Add :recursion

### PR DESCRIPTION
**Pull request by AMHOL**
```ruby
Transproc(:recursion, Transproc(:is, ::Hash, Transproc(:symbolize_keys)))[
  {
    'id' => 1,
    'name' => 'Jane',
    'tasks' => [
      { 'id' => 1, 'description' => 'Write some code' },
      { 'id' => 2, 'description' => 'Write some more code' }
    ]
  }
]
# => {:id=>1, :name=>"Jane", :tasks=>[{:id=>1, :description=>"Write some code"}, {:id=>2, :description=>"Write some more code"}]}
```

### CODE REVIEW

**Comment by splattael** [comment]
@AMHOL I like it!

I have one question about naming: Most (all?) transformations are verbs like `map_keys` or `nest`.
Should `recursion` be named `recur` or something similar? Native speakers to the rescue! :rotating_light:

**Comment by AMHOL** [comment]
That makes sense, although if we were to move that way, we would need a couple of breaking changes (`hash_recursion` => `hash_recur`, `array_recursion` => `array_recur`), also, not keen on the latter method names

**Comment by solnic** [comment]
nah it's not any kind of a convention, fns can be called whatever, it's good when the names communicate what a given fn does. :)

**Comment by solnic** [comment]
@AMHOL could you update CHANGELOG in master pweety please? :)

**Comment by solnic** [comment]
ps. dooh you did that already in this PR, n/m then

**Comment by splattael** [comment]
:+1:

**Pull request merged**
