### PR TITLE
Readme: Remove a non-desired parenthesys from example code

### PR DESCRIPTION
**Pull request by makevoid**
causing:

```
syntax error, unexpected ')', expecting end-of-input (SyntaxError)
```

:)

### CODE REVIEW

**Comment by makevoid** [comment]
hmm I used github's edit button and it didn't let me choose the branch name, you way want to edit it yourself maybe and close this :)

**Comment by makevoid** [comment]
oh I just closed it, anyway it's an awesome library! 

```rb
T_FOO = Transproc(:hash_recursion, Transproc(:symbolize_keys)) + Transproc(:hash_recursion, Transproc(:map_hash, foo: :bar))
T_FOO.( foo: "baz", child: { "foo" => "asd"  } )
```
too awesome to be true!
to not talk about coercions, whoa!

probably a readme taken from the specs would be cool!

thanks!

**Comment by solnic** [comment]
@makevoid hah thanks Francesco :) I'll be working on a new readme and maybe even a website for this project. This is a crucial piece used by ROM :)

**Comment by AMHOL** [comment]
FYI: The code example could be written like this:

```ruby
fn = Transproc(:hash_recursion, Transproc(:symbolize_keys) + Transproc(:map_hash, foo: :bar))
fn[foo: "baz", child: { "foo" => "asd"  }] #=> {:child=>{:bar=>"asd"}, :bar=>"baz"}
```
To avoid having multiple hash-recursion calls in there

**Comment by makevoid** [comment]
@solnic  you still need to remove the extra paren from the line in the readme https://github.com/solnic/transproc/commit/6c042b4342c4a249a2c0e59d41ce5718c1515506#diff-04c6e90faac2675aa89e2176d2eec7d8R42 

there's an extra `)` at the end :)

**Comment by solnic** [comment]
huh right, fixed thanks :)

**Pull request closed without merging**
