### PR TITLE
WIP Perf tweaks

### PR DESCRIPTION
**Pull request by solnic**

### CODE REVIEW

**Comment by splattael** [comment]
As @solnic mentioned on Gitter:

```
TypeError:
       can't dump anonymous class #<Class:0x007fcd3f9ae728>
     # /Users/solnic/Workspace/transproc/lib/transproc/array.rb:182:in `dump'
     # /Users/solnic/Workspace/transproc/lib/transproc/array.rb:182:in `combine'
     # /Users/solnic/Workspace/transproc/lib/transproc/function.rb:47:in `call'
     # /Users/solnic/Workspace/transproc/lib/transproc/function.rb:47:in `call'
     # /Users/solnic/Workspace/transproc/lib/transproc/composite.rb:30:in `call’
```

> rom passes Relation::Loaded there and it may contain all sorts of stuff so Marshal (or any kind of copying is a no-go

:skull: `Marshal.dump/load`

**Comment by AMHOL** [comment]
Purely out of interest as I'm sure there's good reason, why was `Marshal.load(Marshal.dump(hash))` used?

**Comment by splattael** [comment]
@AMHOL I used `Marshal#dump/load` to deep copy the input to speed up `#combine`.
As @solnic pointed out (and I knew it already kind of) it breaks so it's not a option.

**Comment by AMHOL** [comment]
Ahh OK cool

**Comment by solnic** [comment]
Closing this as @Kukunin tweaked it in #90 and it's super fast :)

**Pull request closed without merging**
