### PR TITLE
Fix `to_ast` for registered composed functions

### PR DESCRIPTION
**Pull request by splattael**
:construction: WIP

Registered, composed functions did not work before this commit.

I feel that my fix is just a hack and need some :eyes:

Discussion is needed!

/cc @solnic @AMHOL

### CODE REVIEW

**Comment by AMHOL** [comment]
:+1: looks good to me

**Comment by solnic** [comment]
This isn't right. `register` shouldn't wrap a composite function in another function. So this is more a bug in the register logic.

**Comment by solnic** [comment]
...actually, a bug in the fn access logic which is the place where `Transproc::Function.new` takes place

**Comment by splattael** [comment]
This PR fights with #21. Let's start over.

**Pull request closed without merging**
